apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-config
data:
{{- if .Values.report.enabled }}
  REPORT_API_BASE_URL: {{ quote .Values.report.api.baseUrl }}
{{- end }}
{{- if .Values.notify.enabled }}
  NOTIFY_API_BASE_URL: {{ quote .Values.notify.api.baseUrl }}
{{- end }}
{{- if .Values.auth.enabled }}
  KEYCLOAK_URL: {{ quote .Values.auth.api.baseUrl }}
{{- end }}
{{- if .Values.expose.enabled }}
  EXPOSE_API_BASE_URL: {{ quote .Values.expose.api.baseUrl }}
  EXPOSE_CLIENT_BASE_URL: {{ quote .Values.expose.client.baseUrl }}
{{- end }}
{{- if .Values.databox.enabled }}
  DATABOX_API_BASE_URL: {{ quote .Values.databox.api.baseUrl }}
  DATABOX_CLIENT_BASE_URL: {{ quote .Values.databox.client.baseUrl }}
{{- end }}
{{- if .Values.uploader.enabled }}
  UPLOADER_API_BASE_URL: {{ quote .Values.uploader.api.baseUrl }}
  UPLOADER_CLIENT_BASE_URL: {{ quote .Values.uploader.client.baseUrl }}
{{- end }}
{{- if .Values.dashboard.enabled }}
  DASHBOARD_BASE_URL: {{ quote .Values.dashboard.baseUrl }}
  DISPLAY_SERVICES_MENU: {{ ternary "true" "false" .Values.dashboard.menuEnabled | quote }}
{{- end }}
