{{- if .Values.databox.enabled }}
{{- with .Values.databox.client.oauthClient }}
{{- if not .externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: databox-oauth-client-secret
stringData:
  CLIENT_ID: {{ .id | quote }}
  CLIENT_SECRET: {{ .secret | quote }}
{{- end }}
{{- end }}
{{- end }}
