{{- with .Values.uploader.client.oauthClient }}
{{- if not .externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: uploader-oauth-client-secret
stringData:
  CLIENT_ID: {{ .id }}_{{ .randomId }}
  CLIENT_SECRET: {{ .secret | quote }}
{{- end }}
{{- end }}
